[build]
  publish = "."
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"
  AWS_LAMBDA_JS_RUNTIME = "nodejs20.x"

[[redirects]]
  from = "/"
  to   = "/USFORCE8.html"
  status = 200

# Força HTTPS
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
